=== sergiomanr/Practica5_Blog_TECW/UPM/Bases_no_rel/Práctica2-XML/viaje.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace='https://upm.es/viaje'
    xmlns:tns='https://upm.es/viaje'
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault='qualified'>
    <xs:element name='viaje'>   
        <xs:complexType>
            <xs:all>
                <xs:element name='datos'>
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="fecha-inicio" type="xs:date"/>
                            <xs:element name="fecha-fin" type="xs:date"/> 
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name='viajeros'>
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="10">
                            <xs:element name="viajero" type="tns:viajerosinfo"/>
                        </xs:sequence>
                    </xs:complexType>   
                </xs:element>
                <xs:element name='paises'>
                    <xs:complexType>
                        <xs:sequence maxOccurs="10">
                            <xs:element name='pais'>
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name='nombre' type="xs:string" />
                                        <xs:element name='numero-ciudades-visitadas' type="xs:int"/>
                                        <xs:element name="poblacion" type="xs:double"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name='kilometros-viajados'>
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="0"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>               
                <xs:element name='hoteles'>
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="10">
                            <xs:element name="hotel">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="nombre"/>
                                        <xs:element name="precio-noche" type="xs:decimal"/>
                                        <xs:element name="personas-habitacion">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minExclusive value="0"/>
                                                    <xs:maxInclusive value="4"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="ciudad"/>
                                    </xs:all>
                                    <xs:attribute name="pais" use="required" /> 
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="viajerosinfo">
        <xs:sequence>
            <xs:element name="nombre-viajero" type="xs:string"/>
            <xs:element name="DNI">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{8}[A-Z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="fecha-nacimiento" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== sergiomanr/Practica5_Blog_TECW/UPM/Bases_no_rel/Práctica1-SergioManrique/viaje.xml
<?xml version="1.0" encoding="UTF-8"?>

<viaje xmlns="https://upm.es/viaje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://upm.es/viaje viaje.xsd"
    >
     
    <datos>
        <fecha-inicio>2023-07-23</fecha-inicio>
        <fecha-fin>2023-08-20</fecha-fin>
    </datos>
    <viajeros>
        <viajero>
            <nombre-viajero>Pepe Luis</nombre-viajero>
            <DNI>03036574J</DNI>
            <email>pepeperesluis@gmail.com</email>
            <fecha-nacimiento>1974-09-30</fecha-nacimiento>
        </viajero>
        <viajero>
            <nombre-viajero>Jose Luis Botella</nombre-viajero>
            <DNI>04568768A</DNI>
            <email>jluisbotella@gmail.com</email>
            <fecha-nacimiento>1986-10-08</fecha-nacimiento>
        </viajero>
        <viajero>
            <nombre-viajero>Mario García</nombre-viajero>
            <DNI>75308418P</DNI>
            <email>mario12garcia@hotmail.com</email>
            <fecha-nacimiento>2010-04-22</fecha-nacimiento>
        </viajero>
        <viajero>
            <nombre-viajero>Lucia Pérez Fernandez</nombre-viajero>
            <DNI>96482675G</DNI>
            <email>luperezfer@gmail.com</email>
            <fecha-nacimiento>1990-12-02</fecha-nacimiento>
        </viajero>
    </viajeros>
    <paises>
        <pais>
            <nombre>Austria</nombre>
            <numero-ciudades-visitadas>2</numero-ciudades-visitadas>
            <poblacion>8956000</poblacion>
        </pais>
        <pais>
            <nombre>Hungría</nombre>
            <numero-ciudades-visitadas>1</numero-ciudades-visitadas>
            <poblacion>9710000</poblacion>
        </pais>
    </paises>
    <kilometros-viajados>2022.56</kilometros-viajados>
    <hoteles>
        <hotel pais='Austia'>
            <nombre>Four Seasons Austria</nombre>
            <precio-noche>1500</precio-noche>
            <personas-habitacion>2</personas-habitacion>
            <ciudad>Vienna</ciudad>
        </hotel>
        <hotel pais='Austia'>
            <nombre>Best Western Plus Plaza Hotel Graz</nombre>
            <precio-noche>120.12</precio-noche>
            <personas-habitacion>3</personas-habitacion>
            <ciudad>Graz</ciudad>
        </hotel>
        <hotel pais='Hungría'>
            <nombre>FOUR SEASONS HOTEL GRESHAM PALACE BUDAPEST</nombre>
            <precio-noche>750.62</precio-noche>
            <personas-habitacion>4</personas-habitacion>
            <ciudad>Budapest</ciudad>
        </hotel>
    </hoteles>
</viaje>
